### ISSUE TITLE
distgo: pass arguments to docker build

### ISSUE THREAD

**Issue by bluekeyes** [palantir/godel#154]
I recently started using the `docker` task to build images and discovered it would be helpful to pass arguments to the `docker build` command. In my case, I wanted to use the `--build-arg` flag to pass in the version of the project being built.

The most flexible solution would probably be something similar to the `build-args-script` option in the `build` configuration, but I'd also be happy with a limited option to provide only the project version. Maybe a `version-arg: <argument name>` option or something?

**Comment by bmoylan** [comment]
@yvdinesh

**Comment by yvdinesh** [comment]
@bluekeyes to confirm these arguments are to be passed to `docker build` right?

**Comment by bluekeyes** [comment]
Correct, in particular the [`--build-arg` option](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg).

**Comment by bluekeyes** [comment]
Thanks @yvdinesh, I'll try this in my project once the next release is out.
