### ISSUE TITLE
outparamcheck incorrectly says parameter requires '&'

### ISSUE THREAD

**Issue by freshvolk** [palantir/godel#226]
The following function will cause `outparamcheck` to error with the message: `// 2nd argument of 'Unmarshal' requires '&'`. This seems incorrect as the type of `t` is `*Test` which is already a pointer to a struct.

```go
func hmm() {
	type Test struct {
		test bool
	}
	t := &Test{}
	err := yaml.Unmarshal([]byte("test: true"), t)
	if err != nil {
		panic(err)
	}
}
```

**Comment by adamliesko** [comment]
That needs to be fixed within https://github.com/adamliesko/outparamcheck

**Comment by nmiyake** [comment]
Thanks @adamliesko for fixing the underlying issue! Updated the plugin and program accordingly, so the next version of the release will fix the behavior observed/described here.

**Comment by nmiyake** [comment]
Version 2.8.0 of gödel has been released and contains this fix. Thanks!
