### ISSUE TITLE
docker publish tags should be more consistent

### ISSUE THREAD

**Issue by gdearment** [palantir/godel#228]
Currently, `./godelw docker publish` will only publish the image with the `./godelw project-version` tag and not the tag specified in the `godel/config/dist.yml` docker section. 

I would expect that it would publish both. Additionally, it would also be nice to have a way to specify whether you wanted to update the `latest` tag, under some conditions. For instance, if the build is a release (as opposed to develop or snapshot), it would be nice to specify a different tag, or provide additional tags via command line flags (`./godelw docker dist --tags latest`)

**Comment by nmiyake** [comment]
gödel 2.0 provides much more control over Docker tags now. The gödel product Docker configuration now has a `tag-templates` section where you can explicitly specify how the images should be tagged.

The template supports the variables `{{Product}}`, `{{Version}}` and `{{Repository}}`. I believe that the combination of explicitly specifying templates and providing these template variables should address the use cases outlined in this issue, so closing.
