### ISSUE TITLE
Do not truncate startup log in default SLS init start

### ISSUE THREAD

**Issue by jonsyu1** [palantir/godel#237]
The default `slsDistInitSh` [truncates the startup log](https://github.com/palantir/godel/blob/0.28.0/apps/distgo/cmd/dist/slsdist.go#L93) on init start. If the application dumps a crashlog to stdout on exit, the next startup of the application will truncate the crashlog.

**Comment by nmiyake** [comment]
This operation is now provided by an asset -- if we want to fix this issue, please open an issue on the repository for the asset.
