### ISSUE TITLE
Centralize documentation for configuration

### ISSUE THREAD

**Issue by nmiyake** [palantir/godel#24]
The documentation for configuration files is currently typically split between the example test file, the configuration package (which has the annotations that specify the `YML` keys), and the parameter package (which has the comments/documentation on the entries). Sometimes the package documents are split over multiple files.

Although this may be fine when navigating code, it's non-intuitive and hard to find relevant information when browsing the repository. Should figure out how to centralize and present this information in the `docs` directory.

**Comment by holtwilkins** [comment]
Also, in general, we couldn't find documentation for configuring `check.yml`, for example.

**Comment by ajlake** [comment]
Not having this significantly impacts initial configuration.

**Comment by nmiyake** [comment]
Agreed -- definitely know that there's a need here. Will try to address this over the course of the next week.

**Comment by nmiyake** [comment]
Added some documentation for this at https://github.com/palantir/godel/blob/master/docs/Configuration.md, which is mirrored to https://github.com/palantir/godel/wiki/Configuration. This is meant more as reference documentation than an actual walkthrough/tutorial, which is also definitely needed (and tracked by #23).

Would appreciate feedback on whether this addresses the pain or if there are still gaps here (and if so, what would help to clarify things).
