### ISSUE TITLE
distgo: scripts result in dirty working tree

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#255]
When distgo creates the temporary bash scripts in [script.go](https://github.com/palantir/godel/blob/1.0.0/apps/distgo/pkg/script/script.go#L32) it uses the project directory for the tmpfile which is hard to gitignore. This means that during the script's execution, the working directory is dirty (which results in incorrect `project-version` commands in the script).

**Comment by nmiyake** [comment]
The version is available as the variable `VERSION` and snapshot status is available as `IS_SNAPSHOT` in the script (see https://godoc.org/github.com/palantir/godel/apps/distgo/config#Build). Is that sufficient?

I believe the motivation for the original implementation is to allow the script to run with a well-defined working directory of the project directory.

**Comment by bmoylan** [comment]
So I have a project whose script calls `godel dist` for a different product (because dist dependencies don't exist like build dependencies do) and the inner one is compiled with a dirty version.

**Comment by nmiyake** [comment]
As part of the overhaul for gödel 2.0, the new version of the `distgo` plugin now writes all executable scripts to a temporary directory (uses native Go function for getting temp directory location) before executing them, so that should resolve this issue. Thanks!
