### ISSUE TITLE
test task: access to underlying "go test" config options

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/godel#275]
Is there any way to configure the options passed under the hood to "go test"? The one I need is specifically "-timeout", https://stackoverflow.com/questions/27778280/test-killed-with-quit-ran-too-long

**Comment by nmiyake** [comment]
Fixed in 2.0 -- the new test plugin that provides the `test` task now supports accepting arbitrary arguments to pass through to tests. This is documented at https://github.com/palantir/godel/wiki/Test#run-tests-with-flags.
