### ISSUE TITLE
distgo: manifest-extension regression

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#32]
In 0.9.1 the below `dist.yml` configuration worked, but in 0.11.1 I don't get any extension key in my manifest:

```
    dist:
      input-dir: dist/sls
      output-dir: build/distributions
      dist-type-cfg:
        type: sls
        info:
          service-args: "--config var/conf/product.yaml"
          manifest-extensions:
            product-roles: [ 'admin' ]
```

**Comment by nmiyake** [comment]
Hey sorry that I didn't document/advertise this better -- there were some breaking changes in configuration between 0.9.x and 0.10.x. One of those is that the `dist-type-cfg` key changed to `dist-type`. If you update that key, this should work as expected again.
