### ISSUE TITLE
distgo: add --abbrev=N to git describe command

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#360]
// not sure where distgo went in the 2.0 refactor... this can move somewhere else if need be

It is frustrating when `./godelw project-version` returns different results depending on the environment where it is run. For example, the sha1 abbreviation is often 7 characters in CI systems which do not do full clones but longer in a dev environment with more objects tracked. If we set something like `--abbrev=10` we will likely never hit collisions and have more stable predictable versions.

I know the original intention was to match the behavior of https://github.com/palantir/gradle-git-version but given that projects would never have both build systems in the same git repo, this feels unnecessary.

flagged by @gdearment

**Comment by nmiyake** [comment]
Interesting, thanks for flagging!

I think that the fix here is to just hard-cap the abbreviation at 7 characters. I believe it's the case that the hashes are only used after the tag and number (for example, `0.9.0-11-g8d6bf87`), so it shouldn't serve as a global reference (unless the repo only ever has one tag and every hash follows it), so I don't think that conflicts will be an issue.

I believe that allowing the hash to be longer may result in other issues -- besides matching `gradle-git-version`, I believe that there may be other infrastructure/services that match against the format of "7 SHA-1 characters after `{{version}}-{{number}}-g`, so expanding to 10 may cause other issues.

I will address this specific issue pre-2.0. However, there is also an escape valve where 2.0 allows the logic that is used to compute the version of a project to be specified in configuration (you can specify a script that is run and its output is used as the version string), so in the worst case this can be worked around with configuration.

**Comment by bmoylan** [comment]
Thanks Nick! Using 7 sounds good to me

**Comment by nmiyake** [comment]
PR for fix at https://github.com/palantir/distgo/pull/42.

Note that `abbrev=X` is not sufficient as a workaround since the value is interpreted as "minimum of X" -- there is no option for Git to truncate at X characters if the commit isn't unique at that point, so had to do the logic manually.

However, the "cap commit hash at 7 characters" behavior is what `gradle-git-version` has been doing since November 2017, so this change is consistent with that behavior.

**Comment by nmiyake** [comment]
Updated `distgo` is part of newest `godel` release so this issue is now resolved.
