### ISSUE TITLE
Add documentation for --tags flag for docker build

### ISSUE THREAD

**Issue by markwongsk** [palantir/godel#418]
Godel version: 2.9.1

It is unclear that the `--tags` flag expects a key from the `tags-template` config block. As is there are a couple of undesired behaviors:

1. If the tag does not exist, there's no warning (even in verbose). Docker build just does not execute. But the command is successful. For example:
```
~/go/src/github.palantir.build/rubix/rubix-auth$ ./godelw docker build --dry-run --tags docker.palantir.build/rubix/rubix-test-server --verbose  rubix-test-server
[DRY RUN] Creating distribution for rubix-test-server at test-server/build/distributions/rubix-test-server/0.24.0-27-gf794738.dirty/bin/rubix-test-server-0.24.0-27-gf794738.dirty.tgz
[DRY RUN] Finished creating bin distribution for rubix-test-server
~/go/src/github.palantir.build/rubix/rubix-auth$
```
2. The `--tags` flag behaves differently from the `--tag` flag in vanilla `docker build`. With the lack of documentation of what `--tags` actually is, I believe a reasonable default assumption is to assume proxying towards the underlying command (in this case docker).
```
Flags:
      --dry-run             print the operations that would be performed
  -h, --help                help for build
      --repository string   specifies the value that should be used for the Docker repository (overrides any value(s) specified in configuration)
      --tags stringSlice    
      --verbose             print verbose output for the operation
```

**Comment by nmiyake** [comment]
This is technically an issue on `distgo`, so filed issue there: https://github.com/palantir/distgo/issues/116
