### ISSUE TITLE
running godel check gives "failed to verify checksum for godel-license-plugin"

### ISSUE THREAD

**Issue by jameycribbs** [palantir/godel#430]
Hi!  I have been using godel for several months now and I love it.

Today, when I ran ./godelw check, I got the following error:

"failed to verify checksum for /home/jameycribbs/.godel/plugins/com.palantir.godel-license-plugin-license-plugin-1.0.0: want 5e51f6df8bb3ee77ac25c1c9f9bf84498a34139590efee7ce9deda28d96d52cd, got 7d056eddab884fedc20c9d33aa2a5a509da41485f04e51fe84cbda5424a66de4"

I've been googling around, but did not find any info on how to fix this.  I tried a godel update, but that did not help.  I'm assuming that I must not have the latest version of the license plugin, but when I looked at that repo on github, it looks like it has not been updated recently, so I'm not sure why I just started seeing this error.

Any help on how to fix this would be greatly appreciated!

Jamey

**Comment by nmiyake** [comment]
That's very peculiar -- I wouldn't expect this to suddenly start failing. As a first step, I would try removing `/home/jameycribbs/.godel/plugins/com.palantir.godel-license-plugin-license-plugin-1.0.0` and run the operation again -- that should trigger a re-download of the plugin.

If that doesn't work let me know and I will verify locally to see if I can repro/see if the download for the plugin somehow has a different checksum than expected now.

**Comment by jameycribbs** [comment]
Thanks.  Problem went away.  I really appreciate the work you have done.  I love godel!
