### ISSUE TITLE
Error running ./godelw check compiles

### ISSUE THREAD

**Issue by jameycribbs** [palantir/godel#463]
Go version:  1.13
Godel version: 2.16

When running the "compiles" check, I get:

Running compiles...
../../../../../../../usr/local/go/src/unicode/utf8/utf8.go:28:8: expected ';', found b00000000
../../../../../../../usr/local/go/src/unicode/utf8/utf8.go:64:1: expected 'IDENT', found 'var'
../../../../../../../usr/local/go/src/unicode/utf8/utf8.go:87:1: expected 'IDENT', found 'type'
../../../../../../../usr/local/go/src/unicode/utf8/utf8.go:87:1: missing constant value
...
...
../../../../../../../usr/local/go/src/bytes/reader.go:98:18: DecodeRune not declared by package utf8
../../../../../../../usr/local/go/src/bytes/bytes.go:946:20: DecodeRune not declared by package utf8
../../../../../../../usr/local/go/src/bytes/bytes.go:952:20: DecodeRune not declared by package utf8
../../../../../../../usr/local/go/src/bytes/bytes.go:914:20: DecodeRune not declared by package utf8
...
...

This only started happening on Go 1.13.  I think it might have something in common with this:

https://github.com/golangci/golangci-lint/issues/658

Let me know if I need to supply any more information.  Thanks!

**Comment by nmiyake** [comment]
Yes, it looks like the compiles plugin will need to be updated for Go 1.13 -- will take a look shortly. Thanks for reporting!

**Comment by nmiyake** [comment]
I've released [v1.4.0](https://github.com/palantir/godel-okgo-asset-compiles/releases/tag/v1.4.0) of the "compiles" asset with support for Go 1.13, and have released [v2.17.0](https://github.com/palantir/godel/releases/tag/v2.17.0) of godel, which updates the default assets to use this one. This should resolve the issue of using godel with Go 1.13 (confirmed on projects that use this).

**Comment by jameycribbs** [comment]
Thank you for the quick response and fix!
