### ISSUE TITLE
distgo: opt-in to init.sh reload

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#51]
`init.sh reload` is an optional command for sending a SIGHUP to the application. Unfortunately if you don't handle the SIGHUP, your process dies.

There should be `reload: true` option for distgo which includes the reload command. This will eliminate a reason that applications need to use templates.

**Comment by nmiyake** [comment]
Can you clarify what you mean by this? Just took a look, and from what I can tell the `init.sh` generated for SLS distributions doesn't currently contain a `reload` section: https://github.com/palantir/godel/blob/master/apps/distgo/cmd/dist/slsdist.go#L34

If you can clarify what section needs to be changed/updated, can look into making the fix.
