### ISSUE TITLE
Make godelw script resilient to concurrent downloads

### ISSUE THREAD

**Issue by nmiyake** [palantir/godel#539]
## What happened?
Running `./godelw` concurrently in an environment where the target version of godel referenced by the `godelw` script does not exist can fail because both scripts download and untar the distribution to/from the same file location.

## What did you want to happen?
Running `./godelw` concurrently should succeed even if distribution is not present locally.

## More information
This issue is somewhat similar to #533 and #535, but the main difference is that, in this case, the resolution and conflicts are happening in the logic in the `godelw` script itself. Because this is a script, Go code cannot be used and the solution must be portable. Using a lock file is harder in this scenario because, although programs like [`flock`](https://linux.die.net/man/1/flock) do exist, they are not fully portable -- for example, macOS does not ship with this program.

Locally this issue should be quite rare, as resolving the godel distribution itself is not a very common operation (typically happens once on upgrade) and is not often run in parallel. Also, on failure, re-running will typically succeed because the distribution will then exist locally. This is primarily an issue in environments such as CI.

## Proposed solution
Given the above, I propose a solution in which the distribution is downloaded to a unique location per script and then moved to the destination location after it is verified. The verification is already performed in a unique temporary directory, so this will ensure that concurrent downloads will not write to the same destination. This should significantly reduce the chance of any failures occurring due to race conditions.

**Comment by tabboud** [comment]
An alternative implementation, similar to the lockfile could be to use a locked directory, since `mkdir` should be an atomic operation and should be portable.
For example, if we don't care about blocked waiting and can fail fast then we could do something like this
```bash
if mkdir /some/lock/dir; then
	// not locked
	trap 'rm -rf /some/lock/dir' EXIT
else
	// locked
	exit 1
fi
```

**Comment by nmiyake** [comment]
I considered this approach as well, but didn't think the solution was ideal here because there isn't a good/straightforward way to block on acquiring the lock with this approach. With `flock` or lock files, it's possible to set up behavior such that if a second process attempts to lock the locked portion, it will block until the lock is released. However, with the approach above, I think the only way to really accomplish that is by doing an active wait loop (basically perform the above check in a loop with a sleep between iterations).

**Comment by tabboud** [comment]
If the intention is to block and wait, which is most likely the case for automation systems, then yes I agree. However, if it was humans running the commands it feels sane to just fail fast and expect the user would attempt to re-run. This would basically move the waiting logic up one level and let the users handle it themselves. There are still some edge cases, for example if working on an NFS where `mkdir` might not be atomic, so I am still happy to go with your solution.

**Comment by nmiyake** [comment]
Yes, unfortunately the main motivation/use case here is for automation systems -- this failure case generally isn't a big deal for manual invocation by users because:

1. Users generally won't be running multiple of these operations concurrently in normal workflows
2. Users generally have local cache, so don't run into as many issues with concurrent downloads
3. If a user does encounter one of these concurrency errors, they can typically just rerun the operation again and it will succeed

Unfortunately, automation exacerbates all of these issues:

1. Automation often runs multiple operations in parallel
2. Automation may run in environments that start clean/do not have previous assets cached, which means that more downloads are required
3. In the scenarios above, multiple jobs are often started at the same time, which makes race conditions for downloading the same assets much more likely to be encountered
4. It is much harder to encode retry logic in automation (don't want to blindly retry because legitimate failures shouldn't be ignored and context can't be examined etc.)

Because of this, the main thing I'm looking for is a blocking mechanism or mechanisms that will allow the operations to succeed without failure.
