### ISSUE TITLE
Publish develop builds to -dev in almanac

### ISSUE THREAD

**Issue by jared2501** [palantir/godel#57]
It looks like if I have the following git history:

```
A  <- develop
|
B <- 1.0.0
|
C
|
...
```

And I run a `./godelw publish` on A, then instead of publishing revision 0 to the almanac version 1.0.0-dev, I get a publication that is to revision 1 of 1.0.0

**Comment by nmiyake** [comment]
@jared2501 , in the picture above, what is `develop`? Is it a Git tag, or just a branch? Versioning is done based on the most recent Git tag, so unless `develop` is a tag, I think this is expected behavior (pretty sure it matches behavior of https://github.com/palantir/gradle-git-version since both of these are based on output of `git describe`)

**Comment by jared2501** [comment]
develop is a branch...

**Comment by jared2501** [comment]
most existing projects for java apply this logic:

```
task almanacPublish(type: com.palantir.almanac.tasks.AlmanacPublish) {
    unit {
        product = project.name
        branch = isRelease() ? getTag() : getTag() + '-dev'
        revision = getCommitCount()
        tags = ['slsv2', 'skylab']
    }
    def urlComponents = [
        'https://artifactory.palantir.build/artifactory',
        isRelease() ? 'internal-dist-release' : 'internal-dist-snapshot',
        project.group.replace('.', '/'),
        project.name,
        project.version,
        project.name + '-' + project.version + '.sls.tgz'
    ]
    publication = urlComponents.join('/')
    metadata 'version', version
}
```

**Comment by nmiyake** [comment]
Ah I see -- the `getTag() + '-dev'` is the part that's not currently implemented. Do you know why this logic isn't in https://github.com/palantir/gradle-git-version? Easy enough to add this, but was hoping to have the behavior of this match the Gradle plugin

**Comment by jared2501** [comment]
Hmm not sure.. I found a couple of projects that apply this behaviour, and a couple that don't.

**Comment by jared2501** [comment]
Closing out since even though majority of internal repos publish to -dev, some don't.
