### ISSUE TITLE
should have a way to print built artifact's version

### ISSUE THREAD

**Issue by holtwilkins** [palantir/godel#61]
Godel has logic to determine if the build is a tag release or a snapshot release and creates the version string accordingly, but has no way to output it.

I have to do something like this to parse it out `./godelw artifacts dist | cut -d '-' -f 2- | sed 's/.tgz//'`.

IMO, `./godelw --version` should print godel's version as it does today, but `./godelw version` should print the artifact's version, not godel's version.  How does that sound @nmiyake ?

**Comment by nmiyake** [comment]
Not sure about the name of the command (we can discuss that further), but agree that having a command that prints the artifact version that would be computed could be useful. Should be pretty easy to add.

**Comment by nmiyake** [comment]
Same as #92 which was just fixed. This will be included in the next release as a command called `project-version`.
