### ISSUE TITLE
distgo: RPM after-install-script not included in RPM

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#62]
I think the argument isn't making it to `fpm`. I have a workaround for my current use case, but will probably take a stab at fixing this soon.

**Comment by nmiyake** [comment]
Individual disters have been split out into their own repositories. I created new disters for all of the previous implementations EXCEPT for the rpm one.

Closing out this issue for now. If an rpm dister would be valuable (or if we need to port one), we should create it as a new dister in its own repo.
