### ISSUE TITLE
Install guide?

### ISSUE THREAD

**Issue by SpokeyWheeler** [palantir/godel#693]
## What happened?

I did a git clone, expecting there to be some sort of install script. I can't find it, and the docs cover everything except installation.

Also, I tried:

go install github.com/palantir/godel@latest
go: downloading github.com/palantir/godel v2.20.0+incompatible
go: finding module for package github.com/spf13/pflag
go: finding module for package github.com/nmiyake/pkg/errorstringer
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/nmiyake/pkg/dirs
go: finding module for package github.com/spf13/cobra
go: finding module for package gopkg.in/yaml.v2
go: finding module for package github.com/palantir/pkg/specdir
go: finding module for package github.com/palantir/pkg/matcher
go: downloading github.com/spf13/pflag v1.0.5
go: finding module for package github.com/termie/go-shutil
go: downloading github.com/spf13/cobra v1.6.1
go: downloading github.com/nmiyake/pkg v1.0.0
go: downloading github.com/nmiyake/pkg/dirs v1.1.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/nmiyake/pkg/errorstringer v1.1.0
go: downloading github.com/palantir/pkg v1.1.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/palantir/pkg/specdir v1.2.0
go: downloading github.com/palantir/pkg/matcher v1.2.0
go: finding module for package github.com/google/go-github/github
go: finding module for package github.com/mholt/archiver
go: finding module for package github.com/palantir/pkg/pkgpath
go: finding module for package gopkg.in/cheggaaa/pb.v1
go: downloading github.com/termie/go-shutil v0.0.0-20140729215957-bcacb06fecae
go: downloading github.com/palantir/pkg/pkgpath v1.2.0
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading gopkg.in/cheggaaa/pb.v1 v1.0.28
go: downloading github.com/mholt/archiver v3.1.1+incompatible
go: found github.com/nmiyake/pkg/dirs in github.com/nmiyake/pkg/dirs v1.1.0
go: found github.com/nmiyake/pkg/errorstringer in github.com/nmiyake/pkg/errorstringer v1.1.0
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
go: found github.com/palantir/pkg/matcher in github.com/palantir/pkg/matcher v1.2.0
go: found github.com/spf13/cobra in github.com/spf13/cobra v1.6.1
go: found gopkg.in/yaml.v2 in gopkg.in/yaml.v2 v2.4.0
go: found github.com/palantir/pkg/specdir in github.com/palantir/pkg/specdir v1.2.0
go: found github.com/spf13/pflag in github.com/spf13/pflag v1.0.5
go: found github.com/termie/go-shutil in github.com/termie/go-shutil v0.0.0-20140729215957-bcacb06fecae
go: found github.com/google/go-github/github in github.com/google/go-github v17.0.0+incompatible
go: found github.com/mholt/archiver in github.com/mholt/archiver v3.1.1+incompatible
go: found github.com/palantir/pkg/pkgpath in github.com/palantir/pkg/pkgpath v1.2.0
go: found gopkg.in/cheggaaa/pb.v1 in gopkg.in/cheggaaa/pb.v1 v1.0.28
go: finding module for package github.com/google/go-querystring/query
go: finding module for package github.com/mattn/go-runewidth
go: finding module for package github.com/pierrec/lz4
go: finding module for package github.com/nwaples/rardecode
go: finding module for package github.com/ulikunitz/xz
go: finding module for package github.com/xi2/xz
go: finding module for package github.com/golang/snappy
go: finding module for package github.com/dsnet/compress/bzip2
go: downloading github.com/dsnet/compress v0.0.1
go: downloading github.com/xi2/xz v0.0.0-20171230120015-48954b6210f8
go: downloading github.com/google/go-querystring v1.1.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/ulikunitz/xz v0.5.11
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/nwaples/rardecode v1.1.3
go: finding module for package golang.org/x/sys/unix
go: downloading golang.org/x/sys v0.3.0
go: found github.com/google/go-querystring/query in github.com/google/go-querystring v1.1.0
go: found github.com/dsnet/compress/bzip2 in github.com/dsnet/compress v0.0.1
go: found github.com/golang/snappy in github.com/golang/snappy v0.0.4
go: found github.com/nwaples/rardecode in github.com/nwaples/rardecode v1.1.3
go: found github.com/pierrec/lz4 in github.com/pierrec/lz4 v2.6.1+incompatible
go: found github.com/ulikunitz/xz in github.com/ulikunitz/xz v0.5.11
go: found github.com/xi2/xz in github.com/xi2/xz v0.0.0-20171230120015-48954b6210f8
go: found github.com/mattn/go-runewidth in github.com/mattn/go-runewidth v0.0.14
go: found golang.org/x/sys/unix in golang.org/x/sys v0.3.0
go: downloading github.com/rivo/uniseg v0.2.0
# github.com/palantir/godel/framework/builtintasks/installupdate
../go/pkg/mod/github.com/palantir/godel@v2.20.0+incompatible/framework/builtintasks/installupdate/install.go:68:27: cannot call pointer method Open on archiver.TarGz

## What did you want to happen?

Something like "./install.sh" in the cloned directory

**Comment by SpokeyWheeler** [comment]
Oh yeah, Merry Christmas! :-)

**Comment by nmiyake** [comment]
The godel project is built and distributed using godel itself -- you can use `./godelw build` to build the binaries and `./godelw dist` to create the distribution artifacts.

You are correct that the documentation at https://github.com/palantir/godel/wiki only covers how to install distributions, so it would probably be a good idea to add a section that describes how to run development versions.

The development workflow is roughly:

1. Make changes to code
2. Ensure that everything works using `./godelw check` or `./godelw verify`, running unit tests, etc.
3. Run `./godelw dist` to create a local distribution and note the path to the TGZ created by the task
4. Use the `./godelw install [path-to-tgz-created-by-dist-task]` or `godelinit --local ` command in the project in which you want to use the development version to verify the updated behavior

Closing this issue as I believe the above should answer the posed question. If not, feel free to comment further or open another issue.
