### ISSUE TITLE
2.72.0 release is missing binary package

### ISSUE THREAD

**Issue by alecthomas** [palantir/godel#697]
## What happened?

2.72.0 release is missing binary download:
https://github.com/palantir/godel/releases/tag/v2.72.0

**Comment by nmiyake** [comment]
Thanks for flagging -- we noticed this yesterday and are actively iterating on it at at #696

**Comment by nmiyake** [comment]
The publish issue has been fixed and release v2.73.0 is available and properly has the binary for download.
