### ISSUE TITLE
Getting "This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'." when running ./godelw check compiles.

### ISSUE THREAD

**Issue by jameycribbs** [palantir/godel#701]
## What happened?

After upgrading Go to 1.20 and Godel to 2.74.0, I'm getting the following when running ./godelw check compiles:

[jameycribbs@jamey-swiftsf31442 dashboards_api]$ ./godelw check compiles
Running compiles...
../../../../../usr/local/go/src/runtime/debuglog.go:296:20: StringData not declared by package unsafe
../../../../../usr/local/go/src/runtime/heapdump.go:159:37: StringData not declared by package unsafe
../../../../../usr/local/go/src/runtime/heapdump.go:202:32: StringData not declared by package unsafe
../../../../../usr/local/go/src/runtime/heapdump.go:204:32: StringData not declared by package unsafe
../../../../../usr/local/go/src/runtime/proc.go:658:16: String not declared by package unsafe
../../../../../usr/local/go/src/runtime/runtime.go:115:33: StringData not declared by package unsafe
../../../../../usr/local/go/src/runtime/string.go:105:17: String not declared by package unsafe
../../../../../usr/local/go/src/runtime/string.go:115:16: String not declared by package unsafe
../../../../../usr/local/go/src/runtime/string.go:121:39: StringData not declared by package unsafe
../../../../../usr/local/go/src/runtime/string.go:163:16: String not declared by package unsafe
../../../../../usr/local/go/src/runtime/string.go:268:16: String not declared by package unsafe
../../../../../usr/local/go/src/runtime/type.go:465:16: String not declared by package unsafe
../../../../../usr/local/go/src/runtime/type.go:474:16: String not declared by package unsafe
-: This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
../../../../../usr/local/go/src/internal/reflectlite/type.go:346:16: String not declared by package unsafe
../../../../../usr/local/go/src/internal/reflectlite/type.go:355:16: String not declared by package unsafe
-: This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
../../../../../usr/local/go/src/reflect/type.go:532:16: String not declared by package unsafe
../../../../../usr/local/go/src/reflect/type.go:541:16: String not declared by package unsafe
-: This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
../../../../../usr/local/go/src/os/file.go:246:27: StringData not declared by package unsafe
-: This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
../../../../../usr/local/go/src/strings/builder.go:48:16: String not declared by package unsafe
../../../../../usr/local/go/src/strings/builder.go:48:30: SliceData not declared by package unsafe
../../../../../usr/local/go/src/strings/clone.go:27:16: String not declared by package unsafe
-: This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
../../../../../usr/local/go/src/net/netip/netip.go:343:28: cannot convert slice (variable of type []byte) to [4]byte
../../../../../usr/local/go/src/net/netip/netip.go:345:30: cannot convert slice (variable of type []byte) to [16]byte
../../../../../usr/local/go/src/net/netip/netip.go:1013:27: cannot convert b (variable of type []byte) to [4]byte
../../../../../usr/local/go/src/net/netip/netip.go:1016:29: cannot convert b (variable of type []byte) to [16]byte
../../../../../usr/local/go/src/net/netip/netip.go:1019:29: cannot convert b[:16] (value of type []byte) to [16]byte
-: This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
../../../../../usr/local/go/src/internal/fuzz/mutator.go:267:13: SliceData not declared by package unsafe
../../../../../usr/local/go/src/internal/fuzz/mutator.go:267:40: SliceData not declared by package unsafe
-: This application uses version go1.19 of the source-processing packages but runs version go1.20 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
Finished compiles

## What did you want to happen?

Godel builds my program just fine.  The Godel checks were working fine before upgrading Go to 1.20.  I'm not sure what the error messages are talking about when they say "This application uses version go1.19...".  Is "application" my source code or the godelw executable?

Thanks!

**Comment by nmiyake** [comment]
Apologies for this -- the issue is that the `compiles` plugin is still built with Go 1.19. We typically turn around the godel updates pretty quickly after Go version updates, but fell behind for Go 1.20 because of other priorities. It's very important to us that this gets fixed quickly and should just be a matter of us going through our standard Go version upgrade procedure, so we will prioritize this and aim to get a version of godel with this issue resolved before tomorrow. Thanks for flagging!

**Comment by jameycribbs** [comment]
Thank you so much for the quick reply!

**Comment by nmiyake** [comment]
We've released v2.75.0, which should resolve the issue (its default `compiles` asset uses a version that should be able to handle Go 1.20 properly).

This version doesn't update all of the assets for Go 1.20, but I believe that the upgrade of the `compiles` asset should solve the biggest issues. We'll have another release of godel soon that updates all default assets to use Go 1.20 (process was slowed down a bit by some behavioral changes introduced in Go 1.20 that interacted poorly with other plugins/assets).
