### ISSUE TITLE
okgo: parsing fails running from symlinked directory

### ISSUE THREAD

**Issue by bluekeyes** [palantir/godel#77]
To make things easier locally, I've created symlinks from my regular code locations to the actual source code in `GOPATH`. This appears to break the error parsing done by `okgo`. For example, assume we have a project in `GOPATH/src/symlink` using godel 0.11.4 with the following `main.go` file:

```go
package main

import (
	"net/http"
)

func main() {
	println("Hello World!")
}
```

Running `./godelw check compiles` fails as expected:

```
$ ./godelw check compiles
Running compiles...
main.go:4:2: "net/http" imported but not used
main.go:4:2: "net/http" imported but not used
```

Now, I create a symlink to this directory:

```
$ cd ~/code
$ ln -s $GOPATH/src/symlink symlink
$ cd symlink
$ ./godelw check compiles
Running compiles...
failed on line 1: line /home/bkeyes/code/symlink/main.go:4:2: "net/http" imported but not used is not valid as the start token for an issue
```

Because the error is correctly detected and the command also works if I fix the error, I think this is only a problem with the `okgo` parser (similar to #10) rather than a fundamental problem with using symlinks in this way.

**Comment by natefinch** [comment]
Symlinks break stuff in go builds. Don't use them.

**Comment by nmiyake** [comment]
I believe this should now be fixed (and if it's not fixed, I agree with the assessment that symlinks shouldn't be used in `GOPATH` and in that case this will be a "Won't Fix").
