### ISSUE TITLE
distgo: figure out how to make cross-compilation work for CGo

### ISSUE THREAD

**Issue by nmiyake** [palantir/godel#8]
Issue reported on a MacOS X/Darwin system.

1. Create a project that uses a Go library that has platform-specific CGo code (example: https://github.com/mattn/go-sqlite3)
2. Configure `distgo` to build the project for `darwin-amd64` and `linux-amd64`
3. Run the `build` command

Expected
-------------
Executable should be created for both platforms

Actual
--------
Build for `linux-amd64` fails:

```
# .../persistence
persistence/init.go:28: undefined: sqlite3.SQLiteDriver
```

Notes
--------
Running `GOOS=linux GOARCH=amd64 go build` fails with the same error, so this is a general issue with cross-compiling CGo libraries in certain scenarios. Need to figure out the underlying issue and assess what a fix would entail (or whether it's even possible).

If it's not possible to fix outright, need to have a story for how to support building and distributing Go projects that use CGo that want cross-platform compilation.

**Comment by tomkozlowski** [comment]
I ran into this same issue with this package: https://github.com/keybase/go-keychain

My builds are running just fine on OSX (i.e. I can build both linux and darwin packages) but failing to build darwin packages on unbuntu build nodes

**Comment by nmiyake** [comment]
Is there any error output you can attach/share?

**Comment by tomkozlowski** [comment]
I got the same error behavior as you when I had `CGO_ENABLED` set to `0`, when I set it to `1` I got compilation errors around not being able to find certain C modules (specific to the package I was using) and the ubuntu container running the build having missing C network packages to execute cgo for the darwin OS, but unfortunately I didn't save the terminal output

**Comment by tomkozlowski** [comment]
This is the error output i'm getting:

```
ubuntu@box207:~/.go_workspace/src/github.com/org/project$ ./godelw dist
Building approvenginxcli for linux-amd64 at /home/ubuntu/.go_workspace/src/github.com/org/project/build/1.0.5-4-g265673d/linux-amd64/approvenginxcli
Building approvenginxcli for darwin-amd64 at /home/ubuntu/.go_workspace/src/github.com/org/project/build/1.0.5-4-g265673d/darwin-amd64/approvenginxcli
Failed to build products required for dist: go install failed: build command [/usr/local/go/bin/go install .] run with additional environment variables [GOOS=darwin GOARCH=amd64] failed with output:
# github.com/org/project/vendor/github.com/keybase/go-keychain
vendor/github.com/keybase/go-keychain/corefoundation_pre1.10.go:11:43: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
 #include <CoreFoundation/CoreFoundation.h>
                                           ^
compilation terminated.
# net
/usr/local/go/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
```

**Comment by nmiyake** [comment]
Ah OK yeah -- in this particular case it looks like, when building for `darwin-amd64`, the C linker is looking for Darwin C headers, which don't exist on the CircleCI box. I think this would probably work if we get the C libraries on that box. If that's the case, then technically this is just environmental and is not a bug with gödel or its CGo settings (unless the build works when using Go without gödel in that same environment, but doesn't sound like that is the case?)

**Comment by tomkozlowski** [comment]
@nmiyake agreed, I think this is a conceptual issue with `cgo` and cross-compilation. not sure if we'd necessarily want godel to validate the usage of the C/golang interface and attempt to install the appropriate headers. Will let you know if i figure out how to get the Darwin C headers onto the CircleCI build node.

Probably not a surprise, but compiling on an OSX machine works fine, as it can cross-compile to linux without complaint. Perhaps the recommended fix/known workaround should be to build on OSX?
