### ISSUE TITLE
distgo: Dist type for single binary

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel#98]
I'd like a story for publishing a single binary (for a single architecture) without a directory structure. `bin` is really `$name-$version/bin/os-arch[*]/binary` where I want an archive just containing `binary` letting the client choose the os/arch from separate artifacts. 

I think we pick from **one** of a couple options for how to publish to maven:
- Publish multiple raw files with the osarch in the product name: `com/palantir/foo/foo-linux-amd64/1.0.0/foo-linux-amd64-1.0.0`
  - If we do this we should make sure to publish and check checksum files.
- Publish multiple zip/tgz's containing a single file `foo` with the osarch in the product name:.
    - `com/palantir/foo/foo-darwin-amd64/1.0.0/foo-darwin-amd64-1.0.0.tgz` containing `foo`
    - `com/palantir/foo/foo-linux-amd64/1.0.0/foo-linux-amd64-1.0.0.tgz` containing `foo`
- Either of the above but with the os/arch in the version instead of the name:
  - binary:
    - `com/palantir/foo/foo/1.0.0-darwin-amd64/foo-1.0.0-darwin-amd64`
    - `com/palantir/foo/foo/1.0.0-linux-amd64/foo-1.0.0-linux-amd64`
  - archive:
    - `com/palantir/foo/foo/1.0.0-darwin-amd64/foo-1.0.0-darwin-amd64.tgz` containing `foo`
    - `com/palantir/foo/foo/1.0.0-linux-amd64/foo-1.0.0-linux-amd64.tgz` containing `foo`
- Maven has an idea of an artifact "[classifier](https://maven.apache.org/pom.html#Dependencies)" that's meant for this (multiple artifacts per version) if we want to use it.
  - binary:
    - `com/palantir/foo/foo/1.0.0/foo-1.0.0-darwin-amd64`
    - `com/palantir/foo/foo/1.0.0/foo-1.0.0-linux-amd64`
  - archive:
    - `com/palantir/foo/foo/1.0.0/foo-1.0.0-darwin-amd64.tgz` containing `foo`
    - `com/palantir/foo/foo/1.0.0/foo-1.0.0-linux-amd64.tgz` containing `foo`

I don't really have a strong preference other than standardizing, so decided to lay out a multiple-choice question 😄 

Thanks in advance! I think I'd be willing to take a stab at this if nobody wants to beat me to it.

**Comment by nmiyake** [comment]
Yup, this is definitely something I've thought about as well -- our approach of publishing a combined artifact that contains all the binaries for different OS/arch combinations is actually more of the edge/minority case than the standard (where you want a different distribution per os/arch with only the binaries for the target). I know that @jdhenke ran into this and worked around it with config.

Would definitely like to do something here. The one thing to think about from design/modeling perspective is whether each of these distributions would be a unique type of dist target, or if a single dist task can create multiple outputs. Right now the code assumes that a single dist type produces a single artifact file, and other code (including what @yvdinesh wrote for the Docker dist type) rely on this assumption, so if we change it there will be other things that we will also have to update/change.

**Comment by nmiyake** [comment]
Took a look, and my preference is for using the "classifiers and archive" approach described above.

Part for creating distributions isn't too bad and have that mostly complete. As currently constituted, this would simply be a new dist type that specifies an OS/Arch to output for and would not modify publish. However, agree that the next step would be to update `publish` such that things would mostly just work if you publish multiple distributions of the same product with different targets.
